FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN chmod +x ./node_modules/.bin/vite

# Hardcode your bot URL here as a fallback
ARG VITE_API_URL=https://whatsapp-bot-whatsapp-bot.a8x5ve.easypanel.host
ENV VITE_API_URL=$VITE_API_URL
RUN npx --no-install vite build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]